#!/usr/bin/env python3
"""
Correlation Analysis for EV-seq vs RNA-seq Data

This script performs correlation analysis between EV-seq and RNA-seq abundance data
for extracellular vesicle DNA content analysis.

Author: Nutticha Silakom
Institution: Chulalongkorn University, Bangkok, Thailand
Program: Bioinformatics and Computational Biology, Graduate School
Version: 1.0.0
Date: December 2025

Analysis Steps:
1. Load merged CPM (Counts Per Million) table
2. Assess data distribution characteristics
3. Compute Spearman rank correlation between EV-seq and RNA-seq signals
4. Perform statistical significance testing

Rationale:
- Count data are typically non-normal and zero-inflated
- Spearman correlation is robust to non-linearity and outliers
- CPM normalization enables comparison across different sequencing depths

Usage:
    python correlation_test.py

Requirements:
    - Python 3.8+
    - numpy >= 1.21.0
    - pandas >= 1.3.0
    - scipy >= 1.7.0

Input:
    - merged_CPM_table.csv (generated by merge_file.py)

Output:
    - Correlation statistics and p-values
    - Data distribution assessment results
"""

import numpy as np
import pandas as pd
from scipy.stats import normaltest, spearmanr
import sys
import os
from datetime import datetime

# Print script information
print("="*60)
print("EV-seq vs RNA-seq Correlation Analysis")
print("Journal of Extracellular Vesicles - Supporting Code")
print("Version 1.0.0")
print(f"Execution time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print("="*60)

# -----------------------------
# Load and validate data
# -----------------------------
# Input data file
data_file = "merged_CPM_table.csv"
data_folder_file = "../data/merged_CPM_table.csv"

# Check for data file in current directory first, then data folder
if os.path.exists(data_file):
    input_path = data_file
elif os.path.exists(data_folder_file):
    input_path = data_folder_file
    print(f"Using data file from data directory: {data_folder_file}")
else:
    print(f"Error: Data file not found")
    print(f"Looked for: {data_file} and {data_folder_file}")
    print("Please ensure the merged CPM table has been generated using merge_file.py")
    sys.exit(1)

try:
    df = pd.read_csv(input_path)
    print(f"Loaded data from {input_path}: {df.shape[0]} features, {df.shape[1]} columns")
except Exception as e:
    print(f"Error loading data file: {e}")
    sys.exit(1)

# Validate required columns
required_cols = ["cpm_evseq", "cpm_srr"]
missing_cols = [col for col in required_cols if col not in df.columns]
if missing_cols:
    print(f"Error: Missing required columns: {missing_cols}")
    print(f"Available columns: {list(df.columns)}")
    sys.exit(1)

# -----------------------------
# Select variables (CPM, not raw counts)
# -----------------------------
ev_cpm = df["cpm_evseq"].values
srr_cpm = df["cpm_srr"].values

# -----------------------------
# Log-transform CPM (handle zeros)
# -----------------------------
ev_log = np.log10(ev_cpm + 1)
srr_log = np.log10(srr_cpm + 1)

# -----------------------------
# Normality test (diagnostic only)
# -----------------------------
k2, p_norm = normaltest(ev_log)
alpha = 1e-3

print(f"Normality test (EV-seq logCPM): p = {p_norm:.3e}")
if p_norm < alpha:
    print("→ Distribution deviates from normality (expected for sequencing data)")
else:
    print("→ Cannot reject normality")

# -----------------------------
# Correlation analysis
# -----------------------------
corr, p_value = spearmanr(ev_log, srr_log)

print("\nSpearman correlation results:")
print(f"ρ (rho) = {corr:.3f}")
print(f"p-value = {p_value:.3e}")
